name: Docker Image CI

on:
  schedule:
    - cron: '0 15 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cache-golang-bullseye:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile.golang-bullseye-cache --tag ghcr.io/jgowdy/golang-bullseye-cache:latest
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Publish the Docker image
      run: docker push ghcr.io/jgowdy/golang-bullseye-cache:latest
  cache-rust-alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile.rust-alpine-cache --tag ghcr.io/jgowdy/rust-alpine-cache:latest
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Publish the Docker image
      run: docker push ghcr.io/jgowdy/rust-alpine-cache:latest
  cache-rust-slim-bullseye:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile.rust-slim-bullseye-cache --tag ghcr.io/jgowdy/rust-slim-bullseye-cache:latest
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Publish the Docker image
      run: docker push ghcr.io/jgowdy/rust-slim-bullseye-cache:latest
